"""content tables: Stacks, Syllabus versions and their imported content

Revision ID: 0001
Revises:
Create Date: 2026-09-26 01:24:29.982175

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0001"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "stacks",
        sa.Column("id", sa.String(length=80), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("current_syllabus_pk", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_stacks")),
    )
    op.create_table(
        "syllabuses",
        sa.Column("pk", sa.Integer(), nullable=False),
        sa.Column("stack_id", sa.String(length=80), nullable=False),
        sa.Column("version", sa.String(length=20), nullable=False),
        sa.Column("schema_version", sa.Integer(), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column(
            "imported_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["stack_id"],
            ["stacks.id"],
            name=op.f("fk_syllabuses_stack_id_stacks"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("pk", name=op.f("pk_syllabuses")),
        sa.UniqueConstraint("stack_id", "version", name=op.f("uq_syllabuses_stack_id_version")),
    )
    # Stacks and Syllabus versions reference each other, so this key is added after both exist.
    op.create_foreign_key(
        op.f("fk_stacks_current_syllabus_pk_syllabuses"),
        "stacks",
        "syllabuses",
        ["current_syllabus_pk"],
        ["pk"],
        ondelete="SET NULL",
    )
    op.create_table(
        "materials",
        sa.Column("pk", sa.Integer(), nullable=False),
        sa.Column("syllabus_pk", sa.Integer(), nullable=False),
        sa.Column("id", sa.String(length=80), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("url", sa.Text(), nullable=False),
        sa.Column("type", sa.String(length=20), nullable=False),
        sa.Column("subject", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["syllabus_pk"],
            ["syllabuses.pk"],
            name=op.f("fk_materials_syllabus_pk_syllabuses"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("pk", name=op.f("pk_materials")),
        sa.UniqueConstraint("syllabus_pk", "id", name=op.f("uq_materials_syllabus_pk_id")),
    )
    op.create_index(op.f("ix_materials_syllabus_pk"), "materials", ["syllabus_pk"], unique=False)
    op.create_table(
        "weeks",
        sa.Column("pk", sa.Integer(), nullable=False),
        sa.Column("syllabus_pk", sa.Integer(), nullable=False),
        sa.Column("id", sa.String(length=80), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("number", sa.Integer(), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("goal", sa.Text(), nullable=False),
        sa.Column("deliverable", sa.Text(), nullable=False),
        sa.Column("interview_checks", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(
            ["syllabus_pk"],
            ["syllabuses.pk"],
            name=op.f("fk_weeks_syllabus_pk_syllabuses"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("pk", name=op.f("pk_weeks")),
        sa.UniqueConstraint("syllabus_pk", "id", name=op.f("uq_weeks_syllabus_pk_id")),
    )
    op.create_index(op.f("ix_weeks_syllabus_pk"), "weeks", ["syllabus_pk"], unique=False)
    op.create_table(
        "lessons",
        sa.Column("pk", sa.Integer(), nullable=False),
        sa.Column("syllabus_pk", sa.Integer(), nullable=False),
        sa.Column("week_pk", sa.Integer(), nullable=False),
        sa.Column("id", sa.String(length=80), nullable=False),
        sa.Column(
            "position",
            sa.Integer(),
            nullable=False,
            comment="Order of the Lesson within the whole Syllabus, from 0.",
        ),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("topics", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("exercise", sa.Text(), nullable=True),
        sa.Column("minutes", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["syllabus_pk"],
            ["syllabuses.pk"],
            name=op.f("fk_lessons_syllabus_pk_syllabuses"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["week_pk"], ["weeks.pk"], name=op.f("fk_lessons_week_pk_weeks"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("pk", name=op.f("pk_lessons")),
        sa.UniqueConstraint("syllabus_pk", "id", name=op.f("uq_lessons_syllabus_pk_id")),
    )
    op.create_index(op.f("ix_lessons_syllabus_pk"), "lessons", ["syllabus_pk"], unique=False)
    op.create_table(
        "milestones",
        sa.Column("pk", sa.Integer(), nullable=False),
        sa.Column("syllabus_pk", sa.Integer(), nullable=False),
        sa.Column("week_pk", sa.Integer(), nullable=False),
        sa.Column("id", sa.String(length=80), nullable=False),
        sa.Column(
            "position", sa.Integer(), nullable=False, comment="Order within its Week, from 0."
        ),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("kind", sa.String(length=20), nullable=False),
        sa.Column("minutes", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["syllabus_pk"],
            ["syllabuses.pk"],
            name=op.f("fk_milestones_syllabus_pk_syllabuses"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["week_pk"], ["weeks.pk"], name=op.f("fk_milestones_week_pk_weeks"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("pk", name=op.f("pk_milestones")),
        sa.UniqueConstraint("syllabus_pk", "id", name=op.f("uq_milestones_syllabus_pk_id")),
    )
    op.create_index(op.f("ix_milestones_syllabus_pk"), "milestones", ["syllabus_pk"], unique=False)
    op.create_table(
        "concepts",
        sa.Column("pk", sa.Integer(), nullable=False),
        sa.Column("syllabus_pk", sa.Integer(), nullable=False),
        sa.Column("lesson_pk", sa.Integer(), nullable=False),
        sa.Column("id", sa.String(length=80), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["lesson_pk"],
            ["lessons.pk"],
            name=op.f("fk_concepts_lesson_pk_lessons"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["syllabus_pk"],
            ["syllabuses.pk"],
            name=op.f("fk_concepts_syllabus_pk_syllabuses"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("pk", name=op.f("pk_concepts")),
        sa.UniqueConstraint("syllabus_pk", "id", name=op.f("uq_concepts_syllabus_pk_id")),
    )
    op.create_index(op.f("ix_concepts_syllabus_pk"), "concepts", ["syllabus_pk"], unique=False)
    op.create_table(
        "lesson_materials",
        sa.Column("lesson_pk", sa.Integer(), nullable=False),
        sa.Column("material_pk", sa.Integer(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["lesson_pk"],
            ["lessons.pk"],
            name=op.f("fk_lesson_materials_lesson_pk_lessons"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["material_pk"],
            ["materials.pk"],
            name=op.f("fk_lesson_materials_material_pk_materials"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("lesson_pk", "material_pk", name=op.f("pk_lesson_materials")),
    )
    op.create_table(
        "milestone_materials",
        sa.Column("milestone_pk", sa.Integer(), nullable=False),
        sa.Column("material_pk", sa.Integer(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["material_pk"],
            ["materials.pk"],
            name=op.f("fk_milestone_materials_material_pk_materials"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["milestone_pk"],
            ["milestones.pk"],
            name=op.f("fk_milestone_materials_milestone_pk_milestones"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("milestone_pk", "material_pk", name=op.f("pk_milestone_materials")),
    )
    op.create_table(
        "questions",
        sa.Column("pk", sa.Integer(), nullable=False),
        sa.Column("syllabus_pk", sa.Integer(), nullable=False),
        sa.Column("lesson_pk", sa.Integer(), nullable=False),
        sa.Column("concept_pk", sa.Integer(), nullable=False),
        sa.Column("id", sa.String(length=80), nullable=False),
        sa.Column(
            "position", sa.Integer(), nullable=False, comment="Order within its Question Bank."
        ),
        sa.Column(
            "type", sa.String(length=20), nullable=False, comment="multiple_choice or written"
        ),
        sa.Column("prompt", sa.Text(), nullable=False),
        sa.Column("choices", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("answer", sa.String(length=1), nullable=True),
        sa.Column("model_answer", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("explanation", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["concept_pk"],
            ["concepts.pk"],
            name=op.f("fk_questions_concept_pk_concepts"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["lesson_pk"],
            ["lessons.pk"],
            name=op.f("fk_questions_lesson_pk_lessons"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["syllabus_pk"],
            ["syllabuses.pk"],
            name=op.f("fk_questions_syllabus_pk_syllabuses"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("pk", name=op.f("pk_questions")),
        sa.UniqueConstraint("syllabus_pk", "id", name=op.f("uq_questions_syllabus_pk_id")),
    )
    op.create_index(op.f("ix_questions_syllabus_pk"), "questions", ["syllabus_pk"], unique=False)
    op.create_table(
        "question_materials",
        sa.Column("question_pk", sa.Integer(), nullable=False),
        sa.Column("material_pk", sa.Integer(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["material_pk"],
            ["materials.pk"],
            name=op.f("fk_question_materials_material_pk_materials"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["question_pk"],
            ["questions.pk"],
            name=op.f("fk_question_materials_question_pk_questions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("question_pk", "material_pk", name=op.f("pk_question_materials")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("question_materials")
    op.drop_index(op.f("ix_questions_syllabus_pk"), table_name="questions")
    op.drop_table("questions")
    op.drop_table("milestone_materials")
    op.drop_table("lesson_materials")
    op.drop_index(op.f("ix_concepts_syllabus_pk"), table_name="concepts")
    op.drop_table("concepts")
    op.drop_index(op.f("ix_milestones_syllabus_pk"), table_name="milestones")
    op.drop_table("milestones")
    op.drop_index(op.f("ix_lessons_syllabus_pk"), table_name="lessons")
    op.drop_table("lessons")
    op.drop_index(op.f("ix_weeks_syllabus_pk"), table_name="weeks")
    op.drop_table("weeks")
    op.drop_index(op.f("ix_materials_syllabus_pk"), table_name="materials")
    op.drop_table("materials")
    op.drop_constraint(
        op.f("fk_stacks_current_syllabus_pk_syllabuses"), "stacks", type_="foreignkey"
    )
    op.drop_table("syllabuses")
    op.drop_table("stacks")
    # ### end Alembic commands ###
