"""learners and invitations: invite-only sign-in (#3)

Revision ID: 0002
Revises: 0001
Create Date: 2026-09-26 03:06:44.403010

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0002"
down_revision: str | Sequence[str] | None = "0001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "invitations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sa.Text(), nullable=False, comment="Lower-cased."),
        sa.Column(
            "invited_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("accepted_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_invitations")),
        sa.UniqueConstraint("email", name=op.f("uq_invitations_email")),
    )
    op.create_table(
        "learners",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("clerk_user_id", sa.String(length=64), nullable=False),
        sa.Column("email", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("active_stack_id", sa.String(length=80), nullable=True),
        sa.Column("time_zone", sa.String(length=64), nullable=True, comment="An IANA name."),
        sa.ForeignKeyConstraint(
            ["active_stack_id"],
            ["stacks.id"],
            name=op.f("fk_learners_active_stack_id_stacks"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_learners")),
        sa.UniqueConstraint("clerk_user_id", name=op.f("uq_learners_clerk_user_id")),
    )
    op.create_index(op.f("ix_learners_email"), "learners", ["email"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_learners_email"), table_name="learners")
    op.drop_table("learners")
    op.drop_table("invitations")
    # ### end Alembic commands ###
